### PR TITLE
Adding some basic documents to help improve compliance with FAIR

### PR DESCRIPTION
**Pull request by oceand1**
I have added a code of conduct and a template for the Citation.
I left the citation for you to fill out with your details as you are the software owner. If you have any question don't hesitate to contact me. 

Relevant motivation and context.:
Part of my task I was appointed in my masters.

### CODE REVIEW

**Comment by joeloskarsson** [comment]
Hi, thank you for your interest in contributing to neural-lam!

It would be great if you could update the PR with the provided PR template, as that allows us to easier understand and track the change. 

Regarding the changes themselves:

* I think the formulation of a code of conduct is something that should be discussed with the community, and not directly added. It would be a good idea to join our slack channel and start a discussion about this there, to make sure anyone interested could have some input on the formulations in it.
* For citation, I would personally prefer if the associated scientific publications were cited (as described in the readme) instead of the software itself. But would be open to adding a citation file if others think it's a good idea.

**Comment by oceand1** [comment]
Hi, I appreciate your feedback. How can I get the PR template again? Or do I need to create a new PR to automatically generate the template.

**Comment by joeloskarsson** [comment]
You can copy it from here: https://github.com/mllam/neural-lam/blob/main/.github/pull_request_template.md?plain=1

**Comment by joeloskarsson** [comment]
I think I will close this for now, and then you can start a discussion with the community about what should be in the code of conduct and re-open this or a new PR with a first proposal based on that.

**Pull request closed without merging**
